### ISSUE TITLE
Exception: $s$$124$$.replace is not a function

### ISSUE THREAD

**Issue by arichiardi** [binaryage/dirac#42]
I have run across this problem after upgrating Chrome, thankfully you have already all the version info but let me know if you need anything else or want me to test some fix:

```
Internal Dirac Error: DevTools code has thrown an unhandled rejection (in promise)
Dirac v0.6.7, Chrome/55.0.2868.3, Linux/?, Backend API/external (449 registrations), Backend CSS/external (403 definitions)
TypeError: $s$$124$$.replace is not a function
    at $clojure$string$replace$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4881:127)
    at $cuerdas$core$replace$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4923:133)
    at $cuerdas$core$escape_html$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4924:296)
    at $dirac$implant$intercom$bootstrap_error_msg$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:5422:211)
    at chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:5444:5177
    at $message$$52$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:5444:677)
    at $c__28935__auto__$$115$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:5444:1724)
    at $cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4861:4674)
    at chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4862:409
    at chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4859:4247
```

Thanks as usual for your work on this ;)

**Comment by darwin** [comment]
This particular problem was fixed by this change:
https://github.com/binaryage/dirac/commit/dff0fbad9f54e096979b792cf3d2fe14afa685ae#diff-802e0604db89c05b2a62e0ca66753f48R51

But even if fixed you would get another error about bootstrapping. I think all will be fine in next Dirac version because I have improved the robustness of it.
