### ISSUE TITLE
Internal Dirac Error: DevTools code has thrown an unhandled exception

### ISSUE THREAD

**Issue by njj** [binaryage/dirac#43]
Hi all, I've been getting this strange error... any ideas?

```
Internal Dirac Error: DevTools code has thrown an unhandled exception
Dirac v0.6.7, Chrome/55.0.2880.0, Mac/10.11.6, Backend API/external (456 registrations), Backend CSS/external (405 definitions)
TypeError: Cannot read property '0' of null
    at $cljs$reader$read_keyword$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4911:394)
    at $cljs$reader$read_delimited_list$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4901:1717)
    at $cljs$reader$read_map$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4906:107)
    at $cljs$reader$read_delimited_list$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4901:1717)
    at $cljs$reader$read_map$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4906:107)
    at $cljs$reader$read_delimited_list$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4901:1717)
    at $cljs$reader$read_map$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4906:107)
    at $cljs$reader$read_delimited_list$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4901:1717)
    at $cljs$reader$read_map$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4906:107)
    at $cljs$reader$read$$ (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4917:2441)
```

**Comment by darwin** [comment]
Did you cut the stack trace? I need to know who is calling `$cljs$reader$read$$`.

**Comment by njj** [comment]
@darwin no that was it

**Comment by darwin** [comment]
hmm, try to poke around by opening internal DevTools to debug Dirac window itself:
https://github.com/binaryage/dirac/blob/master/docs/faq.md#something-broke-how-do-i-debug-dirac-devtools-frontend

(formatting minified javascript sources should be helpful here)

**Comment by darwin** [comment]
Closing for lack of response. Please try the latest Dirac release and report back if this is still an issue.
