### ISSUE TITLE
nrepl error: Error loading dirac.nrepl.middleware

### ISSUE THREAD

**Issue by hipitihop** [binaryage/dirac#46]
`lein repl` console error:
`Error loading dirac.nrepl.middleware: Could not locate dirac/nrepl/middleware__init.class..`

Environment:
[org.clojure/clojure "1.8.0"]
[org.clojure/clojurescript "1.9.229"]
[binaryage/devtools "0.8.2"]
[binaryage/dirac "0.7.2"]

```
:repl-options 
    {:port 8230
     :nrepl-middleware [dirac.nrepl.middleware/dirac-repl]
     :init (do
               (require 'dirac.agent)
               (dirac.agent/boot!))}
```

Error detail:
```
lein repl
Error loading dirac.nrepl.middleware: Could not locate dirac/nrepl/middleware__init.class or dirac/nrepl/middleware.clj on classpath.
12:52:08.602 [main] DEBUG dirac.agent.impl - Booting Dirac Agent...
12:52:08.632 [main] DEBUG dirac.agent.impl - effective config:
 {:log-level "WARN",
 :max-boot-trials 10,
 :initial-boot-delay 1000,
 :delay-between-boot-trials 500,
 :skip-logging-setup false,
 :nrepl-server {:host "localhost", :port 8230},
 :nrepl-tunnel {:host "localhost", :port 8231}}

Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: dirac.nrepl.middleware/dirac-repl in this context, compiling:(/tmp/form-init3155148178228252122.clj:1:1525)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
        at clojure.lang.Compiler.analyze(Compiler.java:6669)
        at clojure.lang.Compiler.analyze(Compiler.java:6625)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3834)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
        at clojure.lang.Compiler.analyze(Compiler.java:6669)
        at clojure.lang.Compiler.analyze(Compiler.java:6625)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3834)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
        at clojure.lang.Compiler.analyze(Compiler.java:6669)
        at clojure.lang.Compiler.access$300(Compiler.java:38)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6269)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
        at clojure.lang.Compiler.analyze(Compiler.java:6669)
        at clojure.lang.Compiler.analyze(Compiler.java:6625)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
        at clojure.lang.Compiler.analyze(Compiler.java:6669)
        at clojure.lang.Compiler.eval(Compiler.java:6924)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: dirac.nrepl.middleware/dirac-repl in this context
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:710)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
        ... 37 more
```

**Comment by darwin** [comment]
Dirac middleware is `dirac.nrepl/middleware` not `dirac.nrepl.middleware/dirac-repl`. The later one was deprecated for many months and I have removed it in 0.7.0 release.

**Comment by hipitihop** [comment]
@darwin My apologies I must have missed that in the release notes. All working now, many thanks.
