### ISSUE TITLE
Sporadic "Assert failed: (instance? WebSocketServer server)"

### ISSUE THREAD

**Issue by arichiardi** [binaryage/dirac#67]
I still need to track this down, but I wanted to report the stacktrace of this, which I receive from the nrepl/agent console.

```
Jun 22, 2017 2:33:38 PM clojure.tools.logging$eval2337$fn__2340 invoke
SEVERE: Unhandled REPL handler exception processing message {:code :cljs/quit, :id 695481fd-8066-4234-877f-7333300ef3e4, :op eval, :session 893f19c0-9ee6-4bb9-bfdb-973ce9b314cc}
java.lang.AssertionError: Assert failed: (instance? WebSocketServer server)
	at dirac.lib.ws_server$get_clients.invokeStatic(ws_server.clj:50)
	at dirac.lib.ws_server$get_clients.invoke(ws_server.clj:50)
	at dirac.lib.ws_server$destroy_BANG_.invokeStatic(ws_server.clj:245)
	at dirac.lib.ws_server$destroy_BANG_.doInvoke(ws_server.clj:243)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at dirac.lib.weasel_server$tear_down_env.invokeStatic(weasel_server.clj:194)
	at dirac.lib.weasel_server$tear_down_env.invoke(weasel_server.clj:192)
	at dirac.lib.weasel_server.WeaselREPLEnv._tear_down(weasel_server.clj:59)
	at dirac.nrepl.utils$evaluate_BANG__STAR_.invokeStatic(utils.clj:138)
	at dirac.nrepl.utils$evaluate_BANG__STAR_.invoke(utils.clj:122)
	at dirac.nrepl.utils$evaluate_BANG_.invokeStatic(utils.clj:148)
	at dirac.nrepl.utils$evaluate_BANG_.invoke(utils.clj:145)
	at dirac.nrepl.piggieback$handle_eval_message_BANG_.invokeStatic(piggieback.clj:63)
	at dirac.nrepl.piggieback$handle_eval_message_BANG_.invoke(piggieback.clj:60)
	at dirac.nrepl.piggieback$handle_nonspecial_nonjoined_message_BANG_.invokeStatic(piggieback.clj:77)
	at dirac.nrepl.piggieback$handle_nonspecial_nonjoined_message_BANG_.invoke(piggieback.clj:70)
	at dirac.nrepl.piggieback$handle_nonspecial_message_BANG_.invokeStatic(piggieback.clj:85)
	at dirac.nrepl.piggieback$handle_nonspecial_message_BANG_.invoke(piggieback.clj:80)
	at dirac.nrepl.piggieback$handle_message_BANG_.invokeStatic(piggieback.clj:92)
	at dirac.nrepl.piggieback$handle_message_BANG_.invoke(piggieback.clj:87)
	at dirac.nrepl.piggieback$handler_job_BANG_.invokeStatic(piggieback.clj:97)
	at dirac.nrepl.piggieback$handler_job_BANG_.invoke(piggieback.clj:94)
	at dirac.nrepl.piggieback$dirac_nrepl_middleware_handler.invokeStatic(piggieback.clj:106)
	at dirac.nrepl.piggieback$dirac_nrepl_middleware_handler.invoke(piggieback.clj:102)
	at clojure.core$partial$fn__5380.invoke(core.clj:2604)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__2644.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$session$fn__2995.invoke(session.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__2644.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__3068.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__5297.invoke(core.clj:2027)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

I will try to add some more info if I discover something else.

**Comment by arichiardi** [comment]
This is actually an op sent by the nRepl client the dirac middleware. It looks like it is sending it too early for the dirac middleware, which is not ready yet. It is not crashing per se so It might be pretty innocuous.
