### ISSUE TITLE
Assert failed: (not (realized? (clojure.core/deref client-ready-promise)))

### ISSUE THREAD

**Issue by p-himik** [binaryage/dirac#69]
The example from https://github.com/binaryage/dirac-sample/blob/master/project.clj#L170-L196 (well, my modification of it for my needs) worked, but each time after a minute or so of using Dirac I receive this from `lein repl-figwheel`:

```
user=> 
Dirac Agent v1.2.14
Connected to nREPL server at nrepl://localhost:8230.
Agent is accepting connections at ws://localhost:8231.

user=> Exception in thread "async-dispatch-1" java.lang.AssertionError: Assert failed: (not (realized? (clojure.core/deref client-ready-promise)))
        at dirac.lib.weasel_server$mark_client_as_ready_BANG_.invokeStatic(weasel_server.clj:21)
        at dirac.lib.weasel_server$mark_client_as_ready_BANG_.invoke(weasel_server.clj:20)
        at dirac.lib.weasel_server$eval19730$fn__19731.invoke(weasel_server.clj:130)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at dirac.lib.weasel_server$on_message.invokeStatic(weasel_server.clj:174)
        at dirac.lib.weasel_server$on_message.invoke(weasel_server.clj:171)
        at clojure.core$partial$fn__5380.invoke(core.clj:2606)
        at dirac.lib.ws_server$on_receive.invokeStatic(ws_server.clj:152)
        at dirac.lib.ws_server$on_receive.invoke(ws_server.clj:146)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.core$apply.invoke(core.clj:652)
        at dirac.lib.ws_server$run_client_job_processing_loop_BANG_$fn__19564$state_machine__7900__auto____19569$fn__19571.invoke(ws_server.clj:164)
        at dirac.lib.ws_server$run_client_job_processing_loop_BANG_$fn__19564$state_machine__7900__auto____19569.invoke(ws_server.clj:164)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__7918.invoke(ioc_macros.clj:986)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__2081$fn__2082.invoke(channels.clj:95)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Aug 04, 2017 10:22:16 PM dirac.lib.nrepl-tunnel-server invoke
SEVERE: [NREPLTunnelServer#1 of [NREPLTunnel#1]] Received a bootstrap timeout from client [WebSocketServerClient#7] :
 {:op :bootstrap-timeout}
```

Should I try to provide a minimal working example with this error? Or can you tell what's happening from the error itself?

**Comment by darwin** [comment]
Is this still an issue? Finally, I could spend some time trying to reproduce it.

**Comment by p-himik** [comment]
I still see it, but much more rarely - like once in a week or two.

**Comment by darwin** [comment]
From the stack-trace it looks like your REPL tries to evaluate some compiled javascript before "weasel client" inside Javascript engine signalled that it is ready to process javascript evaluation requests. I don't fully understand if this could be a valid scenario (WeaselREPLEnv is being called from REPL machinery). I could try to make my code more flexible, when I receive evaluation request while still waiting for client-ready message, instead of asserting right away, I could queue the request and give it some time. And throw after some timeout (to properly raise real cases of troubles).

**Comment by darwin** [comment]
Ah, scrap that previous comment. I just looked at the code in more detail and it looks like we receive weasel-client-ready message twice for some reason. I will about possible scenarios.
