### ISSUE TITLE
Internal Dirac Error TypeError: target.emulationAgent(...).setFocusEmulationEnabled is not a function

### ISSUE THREAD

**Issue by zhanghuabin** [binaryage/dirac#83]
The exception on console as below:

```
Dirac v1.2.40, Chrome/69.0.3497.100, Windows/6.3, Backend API/external/575, Backend CSS/external/454

DevTools code has thrown an unhandled rejection (in promise):
TypeError: target.emulationAgent(...).setFocusEmulationEnabled is not a function
    at InspectorMain.BackendSettingsSync._updateTarget (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/devtools_app.js:544:107)
    at InspectorMain.BackendSettingsSync.targetAdded (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/devtools_app.js:547:26)
    at Array.forEach (<anonymous>)
    at SDK.TargetManager.observeTargets (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/shell.js:5408:159)
    at new InspectorMain.BackendSettingsSync (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/devtools_app.js:542:642)
    at InspectorMain.InspectorMain.run (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/devtools_app.js:531:166)
    at Main.Main._initializeTarget (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/shell.js:10354:12)
---
```

**Comment by darwin** [comment]
You should be running Dirac against current Chrome Canary:
https://github.com/binaryage/dirac/blob/master/docs/faq.md#why-should-i-use-recent-chrome-canary-with-dirac-devtools
